name: 4.19.157_fog_memk_ksu

on:
  workflow_dispatch:
jobs:
  build:
    name: Build 4.19.157_fog_memk_ksu
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout Kernel Source
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
          submodules: recursive
          

      - name: Set up MemKernel as a module (M-OUT) with specified name
        run: |
          curl -LSs "https://raw.githubusercontent.com/Poko-Apps/MemKernel/main/kernel/setup.sh" | bash -s M fog_snipex
          
      - name: Set up Ksu next
        run: |
          curl -LSs "https://raw.githubusercontent.com/KernelSU-Next/KernelSU-Next/next/kernel/setup.sh" | bash -s v3.2.0-legacy

      - name: Verify KernelSU-Next submodule
        run: |
          set -e
          echo "=== KernelSU-Next ==="
          test -f KernelSU-Next/kernel/Kconfig
          test -f KernelSU-Next/kernel/Makefile
          echo "KernelSU-Next source: OK"

          echo "=== drivers/kernelsu ==="
          ls -ld drivers/kernelsu
          echo "Target:"
          readlink drivers/kernelsu

          echo "=== KSU Kconfig ==="
          grep -n "drivers/kernelsu/Kconfig" drivers/Kconfig

          echo "=== KSU Makefile ==="
          grep -n "CONFIG_KSU" drivers/Makefile || true
          

      - name: Setup Build Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y bc bison build-essential ccache curl flex \
            git gnupg gperf libelf-dev libncurses5-dev libssl-dev lzop make \
            optipng pngcrush rsync schedtool squashfs-tools xsltproc zip zlib1g-dev libtinfo5

      - name: Download AOSP Toolchains (Clang + Binutils)
        run: |
          mkdir -p clang gcc64 gcc32
          
          # AOSP Clang r383902
          curl -LO https://android.googlesource.com/platform/prebuilts/clang/host/linux-x86/+archive/refs/tags/android-11.0.0_r35/clang-r383902.tar.gz
          tar -xf clang-r383902.tar.gz -C clang
          rm clang-r383902.tar.gz

          # AOSP GCC 64-bit (Binutils)
          curl -LO https://android.googlesource.com/platform/prebuilts/gcc/linux-x86/aarch64/aarch64-linux-android-4.9/+archive/refs/tags/android-11.0.0_r35.tar.gz
          tar -xf android-11.0.0_r35.tar.gz -C gcc64
          rm android-11.0.0_r35.tar.gz

          # AOSP GCC 32-bit (Binutils)
          curl -LO https://android.googlesource.com/platform/prebuilts/gcc/linux-x86/arm/arm-linux-androideabi-4.9/+archive/refs/tags/android-11.0.0_r35.tar.gz
          tar -xf android-11.0.0_r35.tar.gz -C gcc32
          rm android-11.0.0_r35.tar.gz

      - name: Build image.gz
        run: |
          export PATH="${GITHUB_WORKSPACE}/clang/bin:${GITHUB_WORKSPACE}/gcc64/bin:${GITHUB_WORKSPACE}/gcc32/bin:$PATH"
          export ARCH=arm64
          export SUBARCH=arm64

          # Defconfig Load
          make O=out ARCH=arm64 CC=clang CLANG_TRIPLE=aarch64-linux-gnu- CROSS_COMPILE=aarch64-linux-android- CROSS_COMPILE_ARM32=arm-linux-androideabi- vendor/fog-perf_defconfig

          # Compile Kernel
          make -j$(nproc --all) O=out \
            ARCH=arm64 \
            CC=clang \
            CLANG_TRIPLE=aarch64-linux-gnu- \
            CROSS_COMPILE=aarch64-linux-android- \
            CROSS_COMPILE_ARM32=arm-linux-androideabi-

      - name: Build MemKernel module
        run: |
          set -e

          export PATH="${GITHUB_WORKSPACE}/clang/bin:$PATH"
          export ARCH=arm64
          export SUBARCH=arm64

          make -j$(nproc --all) O=out \
            ARCH=arm64 \
            CC=clang \
            CROSS_COMPILE=aarch64-linux-gnu- \
            CROSS_COMPILE_ARM32=arm-linux-gnueabi- \
            LD=ld.lld \
            AR=llvm-ar \
            NM=llvm-nm \
            OBJCOPY=llvm-objcopy \
            OBJDUMP=llvm-objdump \
            STRIP=llvm-strip \
            M=drivers/memkernel modules
            
      - name: Upload Kernel Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: 4.19.157_fog_snipex_memk_ksu
          path: |
            out/arch/arm64/boot/Image.gz
            out/drivers/memkernel/fog_snipex_memk.ko
           
